#!/bin/bash
#SBATCH -J 04_01_hisat2_bbduk
#SBATCH -p cpu
#SBATCH --output=04_01_hisat2_bbduk.out
#SBATCH --error=04_01_hisat2_bbduk.err
#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=hahahehe@sjtu.edu.cn

# 设置输入目录和输出目录
input_dir="/lustre/home/acct-ioozy/ioozy-user3/FQL/SMTD/B_reference_based/mapping/04_01_hisat2_bbduk/"
output_dir="${input_dir}/map_stat"

# 创建输出目录
mkdir -p "${output_dir}"

# 循环处理所有的 sort.bam 文件
for bamfile in ${input_dir}/*.sorted.bam; do
    # 提取文件名
    filename=$(basename "${bamfile}")
    # 构造输出文件路径
    output_file="${output_dir}/${filename%.*}.flag.txt"
    # 运行 samtools flagstat 并将结果保存到输出文件
    samtools flagstat "${bamfile}" > "${output_file}"
done
